alias rmf='shred -uzn 4'
alias rmd='wipe -rfqQ 8'
alias ls='ls -1 --color'
alias _date='date +"%d/%m/%Y - %H:%M:%S"'
export EDITOR='/usr/bin/vim'
export LANG=en_US.utf8
export EMAIL=mgrainmi@gmail.com

tos()
{
    if [ -d ~/main/.trash ]; then
        cd ~/main/.trash; ls -Al
    fi
}

tm()
{
  echo "aplay /usr/share/sounds/for-script/prompt.wav" | \
  at now + "$1"minute
}

# .bash_history
HISTSIZE=8000
HISTFILESIZE=$HISTSIZE
HISTCONTROL=ignoreboth

_bash_history_sync()
{
    builtin history -a         #1
    HISTFILESIZE=$HISTSIZE     #2
    builtin history -c         #3
    builtin history -r         #4
}

history()                      #5
{
    _bash_history_sync
    builtin history "$@"
}

PROMPT_COMMAND=_bash_history_sync
